"""
Django settings for GIFT project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
print(os.getpid())
#from django.conf.global_settings import LOGIN_REDIRECT_URL


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8p_c_k_@@xiv897fw(n$tf&3bawoa&^p%nyt*dtf3ql@u3x=7z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.1.129']


# Application definition

INSTALLED_APPS = [
   'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'notifications',
    'push_notifications',
    'mygift',
    'table',
    'rest_framework',
    'rest_framework.authtoken',
    'django.contrib.sites',
    'rest_auth',
    'djcelery',
    'allauth',
    'allauth.account',
    'rest_auth.registration',
    'gift_app',
    'fcm_django',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.twitter',
    'allauth.socialaccount.providers.google',
    'oauth2_provider',
    'social.apps.django_app.default',
    'rest_framework_social_oauth2',
    'sorl.thumbnail',
    'Home',   
]
FCM_DJANGO_SETTINGS = {
    "FCM_SERVER_KEY": "AIzaSyCFvZu8LoGniFsVPzzxIU8puMrerHhVlOM",

}

PUSH_NOTIFICATIONS_SETTINGS = {
    "APNS_CERTIFICATE": os.path.join(BASE_DIR,"static/certificates/GiftApnsCertificate.pem"),
 }


BROKER_URL = 'redis://127.0.0.1:6379'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
SITE_ID = 1

MIDDLEWARE_CLASSES  = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'

]
AUNTHETICATION_BACKENDS={
                        "django.contrib.auth.backends.ModelBackEnd",
                        "allauth.account.auth.backends.AuthenticationBackend",
                        'rest_framework_social_oauth2.backends.DjangoOAuth2',
                        #'social.backends.facebook.FacebookAppOAuth2',
                        'social.backends.facebook.FacebookOAuth2', 
                        'social_auth.backends.facebook.FacebookBackend',                       
                        }


#ACCOUNTS_LOGIN_FORM_CLASS=''
FACEBOOK_EXTENDED_PERMISSIONS = ['email']
SOCIALACCOUNT_AUTO_LOGIN=True
ROOT_URLCONF = 'GIFT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social.apps.django_app.context_processors.backends',
                'social.apps.django_app.context_processors.login_redirect',
            ],
        },
    },
]
#SOCIAL_AUTH_FACEBOOK_KEY = '160867774371226'
#SOCIAL_AUTH_FACEBOOK_SECRET = '7a30b71fc01961749dd481af096ea191'
#LOGIN_REDIRECT_URL='gift/v1/userlocation'
LOGIN_REDIRECT_URL = "/mygift/login/"
WSGI_APPLICATION = 'GIFT.wsgi.application'

EMAIL_USE_TLS=True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='smtp.gmail.com'
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
EMAIL_HOST_USER='ageanalytics.test@gmail.com'
EMAIL_HOST_PASSWORD='admin@1991'
EMAIL_PORT=587
EMAIL_USE_TLS= True


FACEBOOK_APP_ID='1708603212787130'
FACEBOOK_API_SECRET='91a5f477e6942ba3dc3327d018ce7918'

GOOGLE_OAUTH2_CLIENT_ID = '697752791370-f5hqqb6uska1hf4isfo91b1rjelocisq.apps.googleusercontent.com'
GOOGLE_OAUTH2_CLIENT_SECRET = 'AIzaSyDGGposslVTRToCXnwTo6r76_3a4QUTxXM'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'gift',
        'USER':'root',
        'PASSWORD':'wAst8Buc',
        'HOST': 'localhost',
        'PORT':'3306'
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
   
}
REST_AUTH_SERIALIZERS = {
    'USER_DETAILS_SERIALIZER': 'gift_app.serializers.UserListSerializer'
}
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR,'static'),
)