"""
Django settings for GIFT project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
print(os.getpid())
#from django.conf.global_settings import LOGIN_REDIRECT_URL


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8p_c_k_@@xiv897fw(n$tf&3bawoa&^p%nyt*dtf3ql@u3x=7z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.1.129']

FCM_DJANGO_SETTINGS = {
    "FCM_SERVER_KEY": "AIzaSyCFvZu8LoGniFsVPzzxIU8puMrerHhVlOM",

}
PUSH_NOTIFICATIONS_SETTINGS = {
    "APNS_CERTIFICATE": os.path.join(BASE_DIR,"static\certificates\Giftcertificate.pem"),
 }

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',    
    'django.contrib.sites',
    'rest_auth',
    'djcelery',
    'allauth',
    'allauth.account',
    'rest_auth.registration',
    'gift_app',
    'fcm_django',
    #'mygift',
    'table',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.twitter',
    'allauth.socialaccount.providers.google',
    'oauth2_provider',
    'social.apps.django_app.default',
    'rest_framework_social_oauth2',
    'sorl.thumbnail',
    'push_notifications',
    'notifications',
    'Home'
]
BROKER_URL = 'redis://127.0.0.1:6379'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
SITE_ID = 1

MIDDLEWARE_CLASSES  = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    

]
AUNTHETICATION_BACKENDS={
                        "django.contrib.auth.backends.ModelBackend",
                        "allauth.account.auth_backends.AuthenticationBackend",
                        'rest_framework_social_oauth2.backends.DjangoOAuth2',
                        #'social.backends.facebook.FacebookAppOAuth2',
                        'social.backends.facebook.FacebookOAuth2', 
                        'social.backends.google.GoogleOAuth2'
                        'social_auth.backends.facebook.FacebookBackend',  
                        'oauth2_provider.backends.OAuth2Backend',                     
                        }

"""SOCIAL_AUTH_PIPELINE = (
    'social.pipeline.social_auth.social_details',
    'social.pipeline.social_auth.social_uid',
    'social.pipeline.social_auth.auth_allowed',
    'social.pipeline.social_auth.associate_by_email',
    'social.pipeline.social_auth.social_user',
    'social.pipeline.user.get_username',
    'social.pipeline.user.create_user',
    'social.pipeline.social_auth.associate_user',
    'social.pipeline.social_auth.load_extra_data',
    'social.pipeline.user.user_details'
)
"""

#ACCOUNTS_LOGIN_FORM_CLASS=''
FACEBOOK_EXTENDED_PERMISSIONS = ['email']
SOCIALACCOUNT_AUTO_LOGIN=True
ROOT_URLCONF = 'GIFT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.contrib.auth.context_processors.auth",
            ]
        }
    }
]

#SOCIAL_AUTH_FACEBOOK_KEY = '160867774371226'
#SOCIAL_AUTH_FACEBOOK_SECRET = '7a30b71fc01961749dd481af096ea191'
#LOGIN_REDIRECT_URL='gift/v1/userlocation'
WSGI_APPLICATION = 'GIFT.wsgi.application'

EMAIL_USE_TLS=True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='smtp.gmail.com'
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
EMAIL_HOST_USER='ageanalytics.test@gmail.com'
EMAIL_HOST_PASSWORD='admin@1991'
EMAIL_PORT=587
EMAIL_USE_TLS= True

#GOOGLE_OAUTH2_CLIENT_ID = '697752791370-f5hqqb6uska1hf4isfo91b1rjelocisq.apps.googleusercontent.com'
#GOOGLE_OAUTH2_CLIENT_SECRET = 'AIzaSyDGGposslVTRToCXnwTo6r76_3a4QUTxXM'

#GOOGLE_OAUTH2_CLIENT_ID = '697752791370-op0lhqjvcg16vf9hrrnrpggpmcak0hoj.apps.googleusercontent.com'
#GOOGLE_OAUTH2_CLIENT_SECRET = 'AIzaSyDGGposslVTRToCXnwTo6r76_3a4QUTxXM'
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '444053886468-4okt3gtklfbm06g8f3immef8feutag56.apps.googleusercontent.com'
#GOOGLE_OAUTH2_CLIENT_SECRET = 'qiICQtSUgBtcViAMg3RhM6-m'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'AIzaSyBholLm7XgtTjEK2MHhVjk7OD1Qxd9Ab2o'

FACEBOOK_APP_ID='1708603212787130'
FACEBOOK_API_SECRET='91a5f477e6942ba3dc3327d018ce7918'
# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'rohini_gift',
        'USER':'root',
        'PASSWORD':'wAst8Buc',
        'HOST': 'localhost',
        'PORT':'3306'
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    
   
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),

    
   
}
REST_AUTH_SERIALIZERS = {
    'USER_DETAILS_SERIALIZER': 'gift_app.serializers.UserListSerializer'
}
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

#STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR,'static'),
)
STATIC_URL = '/static/'