# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-29 12:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('gift_app', '0002_authgroup_authgrouppermissions_authpermission_authtokentoken_authuser_authusergroups_authuseruserper'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftergoalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_start_date', models.DateField(blank=True, null=True)),
                ('goal_end_date', models.DateField(blank=True, null=True)),
                ('goal_hours', models.IntegerField(blank=True, null=True)),
                ('goal_tasks', models.IntegerField(blank=True, null=True)),
                ('completed_hours', models.IntegerField(blank=True, null=True)),
                ('completed_tasks', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'giftergoal_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserCategoryRelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_category_rel_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserChallengeCategoryLocationRelRelCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_challenge_category_location_rel_rel_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('organization', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.CharField(blank=True, max_length=45, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('activation_key', models.CharField(blank=True, max_length=45, null=True)),
                ('hometown', models.CharField(blank=True, max_length=60, null=True)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('gender', models.CharField(blank=True, max_length=45, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('host_permission', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'user_type',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='mychallengerelrel',
            options={'managed': True},
        ),
    ]
