# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-10 09:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gift_app', '0005_auto_20161207_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='GifterFeedback',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('point', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gifter_feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GifterRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gifter_point', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gifter_ranking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HostFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'host_feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HostRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_point', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'host_ranking',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='mychallengerelrel',
            name='challenge_join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 10, 9, 15, 19, 284578, tzinfo=utc)),
        ),
    ]
