# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-13 07:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gift_app', '0005_auto_20161207_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mychallengerelrel',
            name='challenge_join_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 13, 7, 39, 35, 860228, tzinfo=utc)),
        ),
    ]
